version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - jbhannah
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
  - dependency-name: bl
    versions:
    - 4.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
